@startuml

class Principal {
    +main(String[] args)
}

class Matematicas {
    +generarNumeroPiRecursivo(long pasosIniciales, long pasosRestantes, long puntosDentro): double
}

Principal ..> Matematicas : uses

@enduml